
- name: Copy redis repo file
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install redis
  ansible.builtin.yum:
    name: redis
    state: latest

- name: update redis conf file 0.0.0.0
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start redis database
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: true
