- name: Copy mongodb repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb service
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: update mongodb conf file 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: enable and restart mongodb
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: yes

- name: Download and unzip the mongodb content
  ansible.builtin.import_role:
    name: common
    tasks_from: download
  vars:
    GIT_DOWNLOAD: true


#- name: Run a js file containing MongoDB commands with pseudo-idempotency
#  community.mongodb.mongodb_shell:
#    file: "/tmp/mongodb-main/catalogue.js"
#    idempotent: yes
#
#- name: Run a js file containing MongoDB commands with pseudo-idempotency
#  community.mongodb.mongodb_shell:
#    file: "/tmp/mongodb-main/users.js"
#    idempotent: yes


- name: Load Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users
