- name: play for varaiables
  hosts: all
  vars:
    URL: play.example.com
    a: 1000
  tasks:
    -  name: print a value
       ansible.builtin.debug:
         msg: URL - {{URL}}
    - name: print value a
      ansible.builtin.debug:
        msg: a- {{a}}


- name: play from sample vars
  hosts: all
  vars_files:
    - sample.vars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{URL}}