- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Download and unzip the frontend content
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Remove old html web pages
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create HTML Dir
  ansible.builtin.file:
    src: /usr/share/nginx/html
    state: directory

#- name: Copy the html web pages
#  ansible.builtin.copy:
#    src: /tmp/frontend-main/static/
#    dest: /usr/share/nginx/html/
#    remote_src: yes

- name: Unzip the {{COMPONENT}}
  ansible.builtin.unarchive:
    src: /tmp/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /usr/share/nginx/html/
    remote_src: yes


- name: Copy roboshop reverse proxy configuration
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restart nginx

- name: Start nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
  ignore_errors: yes
