- name: setup yum repositories for Rabbit MQ
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install Rabbit MQ and Erlang dependencies
  ansible.builtin.yum:
                  - rabbitmq-server
                  - https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
  state: latest

- name: Start Rabbit Mq service
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd
