
#    # curl -s -L -o /tmp/mysql.zip "https://github.com/roboshop-devops-project/mysql/archive/main.zip"
#    Load the schema for Services.
#
#    # cd /tmp
#    # unzip mysql.zip
#    # cd mysql-main
#  # mysql -u root -pRoboShop@1 <shipping.sql

- name: set up my sql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL server & Ansible MySQl modules
  ansible.builtin.yum:
    name:
    - mysql-community-server
    - MySQL-python
    state: installed


- name: Start MySql Service
  ansible.builtin.systemd:
    name: mysqld
    enabled: true
    state: started

- name: grab mysql default password
  ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: mysql_default_password


- name: check if the new password is working
  community.mysql.mysql_query:
    query: "show databases"
    login_user: root
    login_password: "{{MYSQL_ROOT_PASSWORD}}"
  register: out

- name: Change the default password
  when: out.failed | bool
  block:
    - name: grab mysql default password
      ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
      register: mysql_default_password


#- name: print the default password
#  ansible.builtin.debug:
#    msg: "{{mysql_default_password}}"

- name: Change the My sql default root password
  ansible.builtin.template:
    src: root-pass-reset.sql
    dest: /tmp/root-pass-reset.sql


- name: Change the default password
  ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{mysql_default_password.stdout}}" </tmp/root-pass-reset.sql



- name: check for show plugins
  ansible.builtin.shell: echo 'show plugins;' | mysql -uroot -p"{{MYSQL_ROOT_PASSWORD}}"
  ignore_errors: true
  register: out

- name: uninstall the validate password
  community.mysql.mysql_query:
    query: "uninstall plugin validate_password"
    login_user: root
    login_password: "{{MYSQL_ROOT_PASSWORD}}"
  when: out.rc | int == 0
  ignore_errors: yes


- name: Download and unzip the {{COMPONENT}} content
  ansible.builtin.import_role:
   name: common
   tasks_from: download

- name: load schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_user: root
    login_password: "{{MYSQL_ROOT_PASSWORD}}"
