- name: Setup NodeJS repo
  shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Install Nodejs Service
  ansible.builtin.yum:
   name:
      - nodejs
      - make
      - gcc-c++
   state: latest

- name: App add application user
  ansible.builtin.user:
    name: roboshop

- name: Download and unzip the mongodb content
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Remove old app content
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy App content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
  become_user: roboshop
  
- name: Install nodejs dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

- name: Update Ip address of Mongodb server
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Copy catalogue content
  ansible.builtin.copy:
    src: /home/roboshop/catalogue/systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Start Catalogue service
  ansible.builtin.systemd:
    name: catalogue
    daemon_reload: yes
    state: restarted
    enabled: yes
