- name: Update the Prometheus file
  template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Update the records file
  template:
    src: records.yml
    dest: /opt/prometheus/records.yml

- name: Update the alerts file
  template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml

- name: Update the appAlerts file
  template:
    src: appAlerts.yml
    dest: /opt/prometheus/appAlerts.yml

- name: Restart the Prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
