- name: App add application user
  ansible.builtin.user:
    name: roboshop
  register: app_user_info

- name: Download and unzip the {{COMPONENT}} content
  ansible.builtin.import_role:
    name: common
    tasks_from: download

#- name: Stop {{COMPONENT}} Service
#  ansible.builtin.systemd:
#    name: "{{COMPONENT}}"
#    state: stopped
#  ignore_errors: yes

- name: Remove old app content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Create App Dir
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: directory
  become_user: roboshop

#- name: Copy App content
#  ansible.builtin.copy:
#    src: /tmp/{{COMPONENT}}-main/
#    dest: /home/roboshop/{{COMPONENT}}/
#    remote_src: yes
#  become_user: roboshop

- name: Unzip the {{COMPONENT}}
  ansible.builtin.unarchieve:
    src: /tmp/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
  become_user: roboshop

