- name: Install GoLang dependenies
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Application user setup and download the files
  import_tasks: app-user-setup.yml

- name: Install App dependencies
  ansible.builtin.shell: go mod init {{COMPONENT}} && go get && go build
  args:
    chdir: /home/roboshop/{{COMPONENT}}

- name: Update Ip address of rabbit mq
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: setup service and start service
  import_tasks: systemd.yml