- name: set hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}

- name: Instatll node_exporter
  shell: curl -s https://raw.githubusercontent.com/linuxautomations/labautomation/master/tools/prometheus-node-exporter/install.sh | bash
  when: COMPONENT_TYPE == "APP"