- name: Setup NodeJS repo
  shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Install Nodejs Service
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: latest


- name: Add App user setup
   tasks_from: app-user-setup.yml

#- name: App add application user
#  ansible.builtin.user:
#    name: roboshop
#
#- name: Download and unzip the {{COMPONENT}} content
#  ansible.builtin.import_role:
#    name: common
#    tasks_from: download
#
#- name: Remove old app content
#  ansible.builtin.file:
#    path: /home/roboshop/{{COMPONENT}}
#    state: absent
#
#- name: Copy App content
#  ansible.builtin.copy:
#    src: /tmp/{{COMPONENT}}-main/
#    dest: /home/roboshop/{{COMPONENT}}/
#    remote_src: yes
#  become_user: roboshop

- name: Install nodejs dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Update Ip address of Mongodb server
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service


#- name: Start {{COMPONENT}} service
#  ansible.builtin.systemd:
#    name: "{{COMPONENT}}"
#    daemon_reload: yes
#    state: restarted
#    enabled: yes

- name: Import systemd service
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd