groups:
  - name: Instance Alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          type: instanceAlert
          kind: instanceDown
        annotations:
          summary: "Instance Down - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"
          description: "Instance Down - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"

      - alert: CpuUsageAlert
        expr: CPU Percentage Usage > 80
        for: 2m
        labels:
          severity: critical
          type: InstanceAlert
          kind: cpuHighUsage
        annotations:
          summary: "CPU High usage - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"
          description: "CPU High Usage - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"

      - alert: MemoryUsageAlert
          expr: CPU Percentage Usage > 80
          for: 2m
          labels:
            severity: critical
            type: InstanceAlert
            kind: memoryHighUsage
          annotations:
            summary: "Memory High Usage - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"
            description: "Memory High Usage - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"