groups:
  - name: Instance Alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          type: instanceAlert
          kind: instanceDown
        annotations:
          summary: {%raw%}"Instance Down - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}
          description: {%raw%}"Instance Down - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}

      - alert: CpuUsageAlert
        expr: CPU Percentage Usage > 80
        for: 2m
        labels:
          severity: critical
          type: InstanceAlert
          kind: cpuHighUsage
        annotations:
          summary: {%raw%}"CPU High usage - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}
          description: {%raw%}"CPU High Usage - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}

      - alert: MemoryUsageAlert
          expr: node_memory_used_percent > 80
          for: 2m
          labels:
            severity: critical
            type: InstanceAlert
            kind: memoryHighUsage
          annotations:
            summary: {%raw%}"Memory High Usage - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}
            description: {%raw%}"Memory High Usage - IP - [{{ $labels.instance}}], Name - [{{ $labels.instanceName}}]"{%endraw%}