groups:
  - name: custom
    rules:
      - record: cpuUsagePercentage
        expr: (100 - (avg by (instanceName) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100 ))
      - record: node_memory_used_percent
        expr: 100 - ceil((node_memory_MemFree_bytes / node_memory_MemTotal_bytes * 100))